### ISSUE TITLE
Show protection, conservation and ceiterion field only for when a specific feature class is selected

### ISSUE THREAD

**Issue by frwickst** [City-of-Helsinki/ltj#50]
User story:
> As an   admin I want that I can add on feature form also data considering protected   features:   fields from Protection: regulations, hiking, reported_area, land_area,   water_area, additional_info   + selecting ConservationProgrammes for the feature   + selecting Criterion for the feature.   (Admins will be informed to fill these fields only for protected features.   Information mentioned here should be grouped together in the application and   placed in the bottom of the form if possible)

Things to think about:
- Only show the field if the FeatureClass is marked as a protected class
- Protected classes have a specific string ('SK') to the super_class field
- Add header /section titel before the fields

PS. The fields does not have to be hidden/removed they can also be disabled.

**Comment by SannaElijoki** [comment]
The specific string in super_class field  is 'SK'

**Comment by mingfeng** [comment]
Feature classes have a hierarchical structure, should we check the whole hierarchical tree or is it enough to check the super class of a feature's feature class?

**Comment by mingfeng** [comment]
Currently it determines the protected features as specified by checking the `super_class` of a feature's `feature_class`.

**Comment by SannaElijoki** [comment]
SK as superclass is enough. Actually SK is one of the feature classes (=not only super class) only for historical reasons and will not be used as a feature class. It is left there after conversion from old database to new, and will be deleted from feature class tab at some point (after the last conversion when the database is in production) – in the former database all protected feature classes had this feature class SK, and the actual  feature class (Lsa, Lmm, Natur, LslLT..) was specified in another table where also other fields concerning only SK-features were. We had a similar structure with RK-features (square features). In the new database all feature classes are in the same table, and when superclass SK or RK, there is extra information in another table. So, only SK and RK are real super classes. It is very stable which feature classes belong in these, and new ltj-adminstrators will not change them (superuser will if needed, and this can be done directly to the database without the app, as the changes in numerous code-tables.)
Maybe it would be appropriate to do add these A and B to issue list. What do you think? :
A)	This form https://ltj.dev.hel.ninja/admin/nature/featureclass/Lsa/change/ . The super class pick-list is not needed, it will confuse users and may lead to unreal feature class – super class  -combinations. -> Display super_class field read-only  (I will then write in field information what SK and RK means)

B)	Show fields (Square) number, degree_of_determination and additional_info only when super_class is ‘RK’. These field should be in the bottom of the form. Add header /section titel "RUUTU" before the fields.  (The priority of this low, but since the same thing was done with SK then it is good to have with RK, too).

**Comment by mingfeng** [comment]
@SannaElijoki I'll create new issues for it
